apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ask-canada
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ask-canada
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: wikidb
            - name: POSTGRES_USER
              value: wikiuser
            - name: POSTGRES_PASSWORD
              value: strongpassword
          ports:
            - containerPort: 5432
