apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  namespace: ask-canada
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
        - name: wikijs
          image: ghcr.io/requarks/wiki:2
          env:
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: wikiuser
            - name: DB_PASS
              value: strongpassword
            - name: DB_NAME
              value: wikidb
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: wiki-storage
              mountPath: /wiki/data
      volumes:
        - name: wiki-storage
          persistentVolumeClaim:
            claimName: wiki-pvc
