apiVersion: v1
kind: Service
metadata:
  name: wikijs
  namespace: ask-canada
spec:
  type: NodePort
  selector:
    app: wikijs
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32080
