apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/wiki
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-pvc
  namespace: ask-canada
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
